### ISSUE TITLE
Can't open include file 'boardgame_insert_toolkit_lib.2.00.scad'

### ISSUE THREAD

**Issue by MikiGrit** [IdoMagal/The-Boardgame-Insert-Toolkit#1]
When I load `examples.2.00.scad` file, nothing is shown and in console, it says
```
WARNING: Can't open include file 'boardgame_insert_toolkit_lib.2.00.scad'.
```
Probably a bad name... actual file in the repository is named without the last two zeros...

**Comment by IdoMagal** [comment]
fixed.
