### ISSUE TITLE
Feature request: Option to render labels seperately for multiple extruders

### ISSUE THREAD

**Issue by takras** [IdoMagal/The-Boardgame-Insert-Toolkit#10]
First off, thanks for this wonderful tool. I've made a few inserts based off your previous version (sword & sorcery one for instance), and will continue to use it.

I've tried to alter the source code and contribute that way, but I'm not a maths or geometry person, so had to give up. I do have a feature request.

I use a Prusa MMU and have imported (using BIT v1) the rendered stl's to Tinkercad and dome some manipulation there to separate the label from the box and lid, and placed in it's own stl object. This way I can import it into the slicer and apply different filaments for them, and having the text as another color.

Would it be possible to have an option for this, to render the text as seperate objects, while maintaining the placeholder for the text on the lid/box?

Screenshot from my tinkercad trying to illustrate what I mean:
![Merknad 2020-08-24 090518](https://user-images.githubusercontent.com/4748614/91014154-2c347f00-e5e9-11ea-8ef3-e6cd2659a669.jpg)

The text has been stripped from the lid and seperated to its own layer. For the boxes, I've inverted the hollow text into their own objects, so when printing, it will be filled with its own filament color.

**Comment by IdoMagal** [comment]
Hey. Thanks for the feedback. That sounds like a fine addition. I'll investigate.

**Comment by IdoMagal** [comment]
Checked in with version v3.30. Let me know if that works or if I missed something.

Cheers.

**Comment by takras** [comment]
That was very quickly delivered, awesome.

It works fine for the lid, but the box now seems to be broken. The labels appear to stick to the bottom now instead of where it's supposed to be.

Here's the box with **g_print_mmu_layer = "default";**
![Merknad 2020-08-25 085933](https://user-images.githubusercontent.com/4748614/91142589-56ea0a80-e6b1-11ea-814e-242771cf1a67.jpg)

![Merknad 2020-08-25 090445](https://user-images.githubusercontent.com/4748614/91142963-0b842c00-e6b2-11ea-994e-80beb15f0e9a.jpg)


`[ BOX_SIZE_XYZ,                     [70, 206, 32] ],
            [ ENABLED_B, true],
            [ BOX_COMPONENT, [
                [CMP_COMPARTMENT_SIZE_XYZ,      [67, 67, 31]],
                [ CMP_NUM_COMPARTMENTS_XY,      [1, 3] ],
                [CMP_SHAPE,                     FILLET],
                [CMP_FILLET_RADIUS,             5],
                [LABEL,               
                        [
                            [LBL_TEXT,        [   
                                                ["Test"],
                                                ["Test"],
                                                ["Test"]
                                            ]
                            ],
                            [ LBL_PLACEMENT,     CENTER],
                            [ ROTATION,         20],
                            [ LBL_SIZE,         7],
                            [ POSITION_XY,      [ 0,0]],
                            [ LBL_DEPTH, 1 ]
                        ],
                    ], 
            ]]`

**Comment by IdoMagal** [comment]
That’s probably related to 2.28. I’ll have a look tomorrow.

**Comment by IdoMagal** [comment]
fixed in v2.31
