### ISSUE TITLE
v2.30 - Component Labels

### ISSUE THREAD

**Issue by mdoom23** [IdoMagal/The-Boardgame-Insert-Toolkit#11]
Two fold,
I don't believe a new issue, but I just noticed with latest version.  I was using the LBL_PLACEMENT attribute of component labels. 

When using RIGHT_WALL or LEFT_WALL it currently is just moving the text over to the walls, but not doing an implied z-axis rotation of 90/-90 degrees to actually put text on side walls. See attached screenshot of the simple box with a label on RIGHT_WALL.

In addition, I know v2.08 functionality was added to support multiple labels on lids.  Is there an appetite for adding this functionality on components as well?

Ultimately I'm attempting to put labels on the outsides of boxes, and using components to do so.

![simple_box - right_wall label](https://user-images.githubusercontent.com/2321741/91191169-0dea8400-e6ba-11ea-83ce-a7a735d797e0.png)

**Comment by mdoom23** [comment]
Extra info - Just to show what I've been doing with multiple components (and moving one outside the position of box) to get multiple 'box' labels.
![multi component to do box labels](https://user-images.githubusercontent.com/2321741/91193605-e77a1800-e6bc-11ea-8ca1-4dccd3a121ae.png)

**Comment by IdoMagal** [comment]
The bug is fixed in 2.32.

I'll look into adding more label support.

**Comment by IdoMagal** [comment]
multi-label compartment support added in 2.33

**Comment by IdoMagal** [comment]
Added ability to label the box itself with v2.34

Cheers.

**Comment by mdoom23** [comment]
Thanks for the quick work!
