### ISSUE TITLE
v2.35 - Box Labels - BACK depth inverted

### ISSUE THREAD

**Issue by mdoom23** [IdoMagal/The-Boardgame-Insert-Toolkit#13]
The Depth on box labels when put on the 'BACK' of back seems to extrude outward from the box. I think the direction just needs to be inverted.

You can see in screenshot the lack of depth on the one side.  When exported then it becomes just a flat wall.  Just a simple box test
![simple](https://user-images.githubusercontent.com/2321741/91314871-a34e4c80-e77c-11ea-95e8-205bcf0ec424.png)

**Comment by IdoMagal** [comment]
The example box renders correctly for me.

Can you 

1. render the box "labels" from the examples
2. post your box here.

![image](https://user-images.githubusercontent.com/1166577/91377114-7d07cb80-e7d3-11ea-83f0-6962b475c198.png)

**Comment by mdoom23** [comment]
So good news bad news...

I get same results as you.  Example works fine.  The only things unique in mine was wall thickness of 2 instead of 1.5, and depth of .8 instead of .2, however I tested all combinations and they rendered perfectly.

I narrowed it down to not being about the 'BACK' object as initially figured.  It seems to be that specific character in the font I am using.

However, when I just generate a base text object with that font of that character, it generates identical to any other character/font.  So i'm baffled where it could be failing.

text("C", font = "Freehand Spirit:style=Regular");
![Annotation 2020-08-26 222231](https://user-images.githubusercontent.com/2321741/91380469-abdd6c00-e7ea-11ea-8046-524bcb7fea9f.png)

So, all in all, I think my problem is somehow due to the font I'm using.  Although still baffling how its just that character, but it generates as a normal object.  

I generated a box with every character from this font as a box label, and it truly is limited to that single character.  So, sounds like problem is on my end. :-)  But all in all, still confusing when it generates as text object.
![Annotation 2020-08-26 223115](https://user-images.githubusercontent.com/2321741/91381048-07f4c000-e7ec-11ea-9c25-ccaea35d7536.png)

**Comment by IdoMagal** [comment]
That's unfortunate. You could try hacking the $fn to higher or lower values and see if you get different results. There might be something about that vector that it doesn't like to difference().

**Comment by mdoom23** [comment]
Good call!  Lower $fn did the trick. Didn't even think about that.  Thanks again for your help.  I have no shortage of more ideas for enhancements.  Hope you don't mind all these submissions.  I love how quick you're improving the library.

**Comment by IdoMagal** [comment]
Glad that worked. Feel free to request all of the features. The worst that could happen is nothing.
