### ISSUE TITLE
"Fillet" get's calculated from box bottom, not component bottom

### ISSUE THREAD

**Issue by leberschnitzel** [IdoMagal/The-Boardgame-Insert-Toolkit#19]
Fillets always get calculated from box bottoms and not from component bottoms, that makes them useless if the component part is much higher.
Example Flat Bottom:
![image](https://user-images.githubusercontent.com/39628021/97570655-de246900-19e7-11eb-922e-a9b228a819aa.png)

Example Higher Bottom:
![image](https://user-images.githubusercontent.com/39628021/97570498-d369d400-19e7-11eb-95c7-a9f0b4cf953b.png)

Changing the radius too much causes distortion.
What I would expect is that the bottom of the Fillet always is the bottom of the component.

**Comment by IdoMagal** [comment]
fixed in 2.41

**Comment by leberschnitzel** [comment]
Perfect, just tested it and works like a charm!
