### ISSUE TITLE
BOX_VISULIZATION 

### ISSUE THREAD

**Issue by ebp921** [IdoMagal/The-Boardgame-Insert-Toolkit#20]
Not sure what even to put in for arguments. Also when yo do updates, do you happen to have release notes or tell us what you update? Ive also seen some really amazing code from people, i assume they are mixing openSCAD and your toolkit, like the orleans insert code is amazing and i see some things in it that I just dont see as options in the toolkit. eitherway, yeah couple questions,

**Comment by IdoMagal** [comment]
BOX_VISUALIZATION was an early feature that allowed visualizing how the boxes fit together in openscad. My guess is that it's rotted somewhat.

And, yes, updates have changelists.
