### ISSUE TITLE
Multiple lines of text?

### ISSUE THREAD

**Issue by jeep** [IdoMagal/The-Boardgame-Insert-Toolkit#3]
Is there a way to generate multiple lines of text on a lid? Ideally, I would want it to be another font. I tried adding another label tuple, but that did nothing. If there is a way, can you add it to the documentation? If there is not a way, please consider this a feature request. I think allowing a second label would be good and then the position could be changed manually. Something like this
```
     [   "example 1",
        [
            [ LABEL,
                [
                    [ LBL_TEXT,     "Example title"],
                ]
            ],
            [ LABEL,
                [
                    [ LBL_TEXT,     "Subtitle"],
                    [ POSTION_XY, [12, 34],
                ]
            ],
```

**Comment by IdoMagal** [comment]
Good idea.

This is done as of v2.08. 

Also note that I applied the same concept to components so there's no longer the need to have a BOX_COMPONENTS container. Instead create as many BOX_COMPONENT (singular) as desired.
