### ISSUE TITLE
v2.13 Cutouts Not Cutout all the way

### ISSUE THREAD

**Issue by mdoom23** [IdoMagal/The-Boardgame-Insert-Toolkit#5]
I know cut-outs were all re-done / optimized for v2.13.  Is this the intended behavior?

Previously the cutout was fully to the outside.  Now I have solid walls, with only a minor cutout past the compartment.  
I have my g_wall_thickness set to 2.

Please see attached image of 2.12 vs 2.13 for same code.

![Cut-outs 2 12 vs 2 13](https://user-images.githubusercontent.com/2321741/84318609-515e3900-ab34-11ea-96c9-b82c1c1a928e.png)

EDIT: Attaching scad file if needed.
[Orleans.scad.txt](https://github.com/IdoMagal/The-Boardgame-Insert-Toolkit/files/4761257/Orleans.scad.txt)

**Comment by IdoMagal** [comment]
fixed in 2.14

**Comment by mdoom23** [comment]
Confirmed! Thank you
