### ISSUE TITLE
v2.26 - LID_FIT_UNDER_B - Detent Cutouts No Longer Appearing

### ISSUE THREAD

**Issue by mdoom23** [IdoMagal/The-Boardgame-Insert-Toolkit#9]
v2.26
It appears that detent cutouts no longer appear on bottom of boxes when LID_FIT_UNDER_B is set to True.  Is this expected behavior currently?

I haven't printed a box yet with this version, however I know previously this had caused issues with lids getting stuck on bottom of boxes (or simply unable to fit).

![simple_box](https://user-images.githubusercontent.com/2321741/90961159-8eb44080-e46c-11ea-96a5-527fcfbc7c3c.png)

**Comment by IdoMagal** [comment]
Fixed. From the code it was clearly deliberate although I don't recall why. Possibly legacy change. I'll print out a box and make sure it's reasonable.
